spring:
  application:
    name: smart-cart-reminder

  data:
    mongodb:
      host: localhost
      port : 27017
      database : smartcart

  datasource:
    url: jdbc:h2:mem:smartcart
    driverClassName: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

# Smart Cart Configuration
smart-cart:
  behavioral-analysis:
    pattern-threshold: 3
    prediction-window-hours: 24
    reminder-cooldown-hours: 6
  
  notification:
    max-daily-reminders: 3
    default-reminder-time: "18:00"
    quiet-hours:
      start: "22:00"
      end: "08:00"
logging:
  level:
    com.smartcart: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#  twilio:
#    accountSid: your_twilio_account_sid
#    authToken: your_twilio_auth_token
#    fromNumber: +1234567890
huggingface:
  api-key: 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